export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";

export const PLAYER_UPDATE_DATA = "PLAYER_UPDATE_DATA";
export const PLAYER_RESUME = "PLAYER_RESUME";
export const PLAYER_PAUSE = "PLAYER_PAUSE";

export const SONG_LIST_SET = "SONG_LIST_SET";
export const SONG_LIST_SET_SEARCH = "SONG_LIST_SET_SEARCH";
